### ISSUE TITLE
Gesture over the main unlock screen

### ISSUE THREAD

**Issue by dragonnn** [Rijul-Ahuja/GestureUnlock#2]
Could you add an option to directly enter the gesture over the first screen after unlock the phone? It is frustrating that I need first swipe up and then enter the gesture.

**Comment by Rijul-Ahuja** [comment]
This will hide the clock and the notifications, is that what you want?

**Comment by dragonnn** [comment]
Partly, Gravitbox have options like that with transparency, but this option grays all behind it - it would be better when it would have 100% transparency. Here can you see how it works with Gravitybox http://imgur.com/Q7bs6vq I will have it like this but with 100% transparency.

**Comment by Rijul-Ahuja** [comment]
What is the preference called in GravityBox? Or if you could link me to the code which does this, I'll appreciate it.

**Comment by dragonnn** [comment]
In Lockscreen tweaks it is called Direct Unlock i will try find code for it.

**Comment by dragonnn** [comment]
https://github.com/GravityBox/GravityBox/blob/aba1b76ea112146229d5ac227a15486ff9108e52/src/com/ceco/marshmallow/gravitybox/ModLockscreen.java 359 line it starts I think.

**Comment by Rijul-Ahuja** [comment]
What is the preference value you have activated? See through?

**Comment by dragonnn** [comment]
Yes, see through. But it is still not 100% transparent

**Comment by dragonnn** [comment]
Not sure but maybe the shadow can be found somewhere here https://android.googlesource.com/platform/frameworks/base/+/e38c8e2/packages/Keyguard/res/values

**Comment by Rijul-Ahuja** [comment]
Is the shadow controllable using Bright Lockscreen?
http://repo.xposed.info/module/com.generalbrus.brightlockscreen

**Comment by dragonnn** [comment]
Wha, amazing :D, yes it is! Didn't know this module.

**Comment by Rijul-Ahuja** [comment]
Implemented

**Comment by Rijul-Ahuja** [comment]
This doesn't work as expected when a call is incoming, I am unable to answer the call until I press back or click on return to call. Can you confirm?

**Comment by Rijul-Ahuja** [comment]
^ Can you confirm with the GravityBox option?

**Comment by Rijul-Ahuja** [comment]
I have added a check in the latest version which prevents the gesture entry from being shown if there is an ongoing call.
