### ISSUE TITLE
Drawing area 

### ISSUE THREAD

**Issue by Lazaroth** [Rijul-Ahuja/GestureUnlock#3]
This is a second feature request. That you are able to choose the area you can draw in. Right now it covers a good part of the bottom of the screen, but I would prefer if you can choose anywhere on the screen to draw. Top, bottom, both, you name it.

**Comment by dragonnn** [comment]
Full screen area will be nice too.

**Comment by Rijul-Ahuja** [comment]
If you will look at my other module's XDA thread, this feature is already being considered, but I do not know how to implement it. I will try again today, in light of some new information.

**Comment by dragonnn** [comment]
https://android.googlesource.com/platform/frameworks/base/+/e38c8e2/packages/Keyguard/res/values/dimens.xml check this, maybe it will help

**Comment by Rijul-Ahuja** [comment]
I have tried that, you may want to see the current status here
https://github.com/wasdennnoch/LockMod/issues/1

**Comment by Rijul-Ahuja** [comment]
Okay, so I tried replacing this resource in the dimens.xml by my screen height in dp, it did not work.
`<dimen name="keyguard_security_max_height">450dp</dimen>`

**Comment by dragonnn** [comment]
What about this:
    
    <dimen name="keyguard_security_height">400dp</dimen>
?
Maybe we can play with keyguard_security_view_margin too. Max_height could be similar too css so it doesn't force you dimesions to the value only allows to expand it when it is needed.

**Comment by Rijul-Ahuja** [comment]
Missed that, trying it now.

**Comment by Rijul-Ahuja** [comment]
Awesome, that works!
Thanks a lot, now only to implement it to fit the screen size, which I've been told is impossible.
`<dimen name="keyguard_security_height">400dp</dimen>`

**Comment by Rijul-Ahuja** [comment]
Apparently setting the replacement to be outrageously large does the trick. Thank you for your help!
